### ISSUE TITLE
Establish style guide

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/documentation#40]
Require all jsonnet code to be compliant with `jsonnetfmt` using the default options. For CI/CD pipelines, the command `jsonnetfmt --test **/*.jsonnet` can be used, while autoformatting can be done using `jsonnetfmt -i **/*.jsonnet`.

`jsonnetfmt` is documented at https://jsonnet.org/learning/tools.html.

For YAML files, we should use `yamllint` For CI/CD pipelines, the command `yamllint -f parsable --no-warnings  **/*.yml` can be used. For checking before commiting, `yamllint **/*.yml` will do the trick.

Rule wise, we might opt to make `line-length` a warning instead an error and or increase the character count from 80 to something like 120. Subject to be discussed.

**Comment by corvus-ch** [comment]
In a discussion with @simu we figured that there is already a mess with naming of exported things in libraries:

* The Jsonnet standard library uses camelCasing.
* Kapitan is follwing python conventions and uses snake_case.
* The Kube library follows golang convention and uses PascalCasing
* The commodore library does not follow any consistent style and use camelCase and snake_case.

I suggest to follow the lead of Jsonnet and take camelCase as the standard for exported functions and variables.

**Comment by corvus-ch** [comment]
Consider to also use https://editorconfig.org/. While we can check for this in CI/CD, having an editor config file results in a better developer experience.

**Comment by srueg** [comment]
Possible ideas: https://github.com/databricks/jsonnet-style-guide

**Comment by corvus-ch** [comment]
Closed by #88.
