### ISSUE TITLE
Getting Started on macOS

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/documentation#50]
The how to "Getting Started with Project Syn" does not work on macOS. Docker is not supported natively so most will use Docker for Mac. The way this is set up, messes up networking for most things that just work ™️ on Linux. So this is what one needs to do differently:

1. Use Docker for Mac
2. Enable Kubernetes within its settings
3. Install Nginx ingress
   https://kubernetes.github.io/ingress-nginx/deploy/#docker-for-mac
   
   ```
   kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
   ```
   
   NOTE: This will not work if you have other services running on port 80 and 443 on your macOS.
4. Use localhost for the ingress IP
   ```
   export K3S_INGRESS_IP=127.0.0.1
   ```
5. Use the injected docker service while compiling the cluster catalog
   ```
   export COMMODORE_API_URL=http://$LIEUTENANT_API_SERVICE_HOST
   ```

   NOTE: I was not able to find a way to define COMMODORE_API_URL while starting the Commodore container. So it has to be done once inside the container.

**Comment by tobru** [comment]
See #65
